### ISSUE TITLE
Activate github pages

### ISSUE THREAD

**Issue by as-eldlc** [lecole-ldlc/au_gamer_apaise_dataviz#1]
Please activate github pages (in the settings panel) such that your dataviz is published automatically !

**Comment by GTHamonville** [comment]
Seems like i don't have the rights on the depository. Maybe moving the depository changed the rights owner. I checked on another project and i confirm that i don't have access to the settings page.

**Comment by GTHamonville** [comment]
And i just saw that you are the owner of the depository now.
![2017-11-30_09h25_43](https://user-images.githubusercontent.com/32869393/33420844-71091c7c-d5b0-11e7-9427-4196a2c1cd01.png)

**Comment by as-eldlc** [comment]
I made you admin of the repository, do you confirm you can manage the settings ?

**Comment by GTHamonville** [comment]
Yes I can access the settings page. I'm creating the github page right now. Thank you !
